export { addToCartIcon } from './add-to-cart'
export { menuIcon } from './menu'
export { minusIcon } from './minus'
export { plusIcon } from './plus'
export { removeFromCartIcon } from './remove-from-cart'
